# -------------------------------------------------------------------------------------
# Customizing Output Formats
# See: https://gohugo.io/templates/output-formats/#customizing-output-formats
# -------------------------------------------------------------------------------------

home     = [ "HTML", "RSS", "JSON", "BaiduUrls", "Algolia" ]
page     = [ "HTML", "MarkDown" ]
section  = [ "HTML", "RSS" ]
taxonomy = [ "HTML" ]
term     = [ "HTML", "RSS" ]
