title = "旷野之森"
baseURL = "https://weedien.cn/blog/"
theme = [ "FixIt" ]
defaultContentLanguage = "zh-cn"
languageCode = "zh-CN"
languageName = "简体中文"
hasCJKLanguage = true
paginate = 12
copyright = "weedien"
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true

[menu]
  [[menu.main]]
    identifier = "posts"
    pre = ""
    post = ""
    name = "所有文章"
    url = "/posts/"
    title = ""
    weight = 1
    # FixIt 0.2.14 | NEW add user-defined content to menu items
    [menu.main.params]
      # add css class to a specific menu item
      class = ""
      # whether set as a draft menu item whose function is similar to a draft post/page
      draft = false
      # FixIt 0.2.16 | NEW add fontawesome icon to a specific menu item
      icon = "fa-solid fa-archive"
      # FixIt 0.2.16 | NEW set menu item type, optional values: ["mobile", "desktop"]
      type = ""
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "分类"
    url = "/categories/"
    title = ""
    weight = 2
    [menu.main.params]
      icon = "fa-solid fa-th"
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "标签"
    url = "/tags/"
    title = ""
    weight = 3
    [menu.main.params]
      icon = "fa-solid fa-tags"
  [[menu.main]]
    weight = 4
    identifier = "documentation"
    pre = ""
    name = "文档"
    url = "/categories/documentation/"
    title = ""
  [[menu.main]]
    weight = 5
    identifier = "about"
    pre = ""
    post = ""
    name = "关于"
    url = "/about/"
    title = ""
  [[menu.main]]
    weight = 6
    identifier = "github"
    pre = "<i class='fab fa-github fa-fw' aria-hidden='true'></i>"
    post = ""
    url = "https://github.com/weedien"
    title = "GitHub"

[params]
  version = "0.2.X" # e.g. "0.2.X", "0.2.15", "v0.2.15" etc.
  # site description
  description = "weedien的个人网站"
  keywords = [ "weedien" ]
  defaultTheme = "auto"
  gitRepo = "https://github.com/weedien/blog"
  # ["sha256", "sha384", "sha512", "md5"]
  fingerprint = ""
  dateFormat = "2006-01-02"
  images = [  ]
  enablePWA = false
  externalIcon = false
  disableThemeInject = false

  [params.author]
    name = "weedien"
    avatar = '/images/avatar.png'
    link = 'https://github.com/weedien'
    email = "weedien@qq.com"

  [params.app]
    title = "旷野之森"
    noFavicon = false
    svgFavicon = ""
    iconColor = "#5bbad5"
    tileColor = "#da532c"
    [params.app.themeColor]
      light = "#f8f8f8"
      dark = "#252627"

[params.search]
  enable = true
  type = "algolia"
  contentLength = 4000
  placeholder = ""
  maxResultLength = 10
  snippetLength = 30
  highlightTag = "em"
  absoluteURL = false
  [params.search.algolia]
    index = "weblog"
    appID = "A0JPQ9EYLU"
    searchKey = "5f0c6e179363e5bd7cf787dd23989cc9"

[params.header]
  # ["sticky", "normal", "auto"]
  desktopMode = "sticky"
  # ["sticky", "normal", "auto"]
  mobileMode = "auto"
  [params.header.title]
    logo = ""
    name = "旷野之森"
    pre = "<i class='fa-solid fa-tree'></i>"
    post = ""
    typeit = false
  [params.header.subtitle]
    name = ""
    typeit = false

[params.breadcrumb]
  enable = false
  sticky = false
  showHome = false

[params.footer]
  enable = true
  custom = ""
  hugo = false
  copyright = true
  author = true
  since = "2023"
  wordCount = true
  gov = ""
  icp = "<a href='https://beian.miit.gov.cn/' target='_blank'>湘ICP备2023032380号</a>"
  license = ""
  [params.footer.siteTime]
    enable = false
    animate = true
    icon = "fa-solid fa-heartbeat"
    pre = ""
    value = ""
  # FixIt 0.2.17 | NEW footer lines order, optional values: ["first", 0, 1, 2, 3, 4, 5, "last"]
  [params.footer.order]
    powered = 0
    copyright = 1
    statistics = 2
    visitor = 3
    beian = "last"

[params.section]
  paginate = 20
  dateFormat = "01-02"
  rss = 10
  [params.section.recentlyUpdated]
    enable = false
    rss = false
    days = 30
    maxCount = 10

[params.list]
  paginate = 20
  dateFormat = "01-02"
  rss = 10

[params.tagcloud]
  enable = false
  min = 14         # Minimum font size in px
  max = 32         # Maximum font size in px
  peakCount = 10   # Maximum count of posts per tag
  orderby = "name" # Order of tags, optional values: ["name", "count"]

[params.home]
  rss = 10
  [params.home.profile]
    enable = true
    gravatarEmail = ""
    avatarURL = "/images/avatar.png"
    avatarMenu = ""
    title = "weedien"
    subtitle = "喜欢摆烂、不务正业的程序员"
    typeit = true
    social = true
    disclaimer = ""
  [params.home.posts]
    enable = true
    paginate = 6

[params.social]
  GitHub = "weedien"
  CSDN = ""
  Email = "weedien@qq.com"
  RSS = false

# FixIt 0.2.0 | CHANGED Page config
[params.page]
  authorAvatar = true
  hiddenFromHomePage = false
  hiddenFromSearch = false
  hiddenFromRss = false
  twemoji = false
  lightgallery = false
  ruby = true
  fraction = true
  fontawesome = true
  # license = '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">CC BY-NC-SA 4.0</a>'
  linkToMarkdown = false
  rssFullText = false
  # FixIt 0.2.13 | NEW Page style ["narrow", "normal", "wide", ...]
  pageStyle = "normal"
  # If true, save the reading progress when closing the page.
  autoBookmark = false
  wordCount = true
  readingTime = true
  endFlag = ""
  instantPage = false

  [params.page.repost]
    enable = false
    url = ""
  [params.page.toc]
    enable = true
    keepStatic = false
    auto = true
    position = "right"
  [params.page.expirationReminder]
    enable = false
    reminder = 90
    warning = 180
    closeComment = false
  [params.page.math]
    enable = true
    # default inline delimiter is $ ... $ and \( ... \)
    inlineLeftDelimiter = ""
    inlineRightDelimiter = ""
    # default block delimiter is $$ ... $$, \[ ... \], \begin{equation} ... \end{equation} and some other functions
    blockLeftDelimiter = ""
    blockRightDelimiter = ""
    # KaTeX extension copy_tex
    copyTex = true
    # KaTeX extension mhchem
    mhchem = true
  [params.page.code]
    copy = true
    edit = false
    maxShownLines = 20
  [params.page.edit]
    enable = false
    # FixIt 0.2.15 | CHANGED Link for fork & edit
    # url = "/edit/branch-name/subdirectory-name" # base on `params.gitRepo`
    # url = "https://github.com/user-name/repo-name/edit/branch-name/subdirectory-name" # full url
    url = ""
  # FixIt 0.2.0 | NEW Mapbox GL JS config (https://docs.mapbox.com/mapbox-gl-js)
  [params.page.mapbox]
    # access token of Mapbox GL JS
    accessToken = ""
    # style for the light theme
    lightStyle = "mapbox://styles/mapbox/light-v9"
    # style for the dark theme
    darkStyle = "mapbox://styles/mapbox/dark-v9"
    # whether to add NavigationControl
    navigation = true
    # whether to add GeolocateControl
    geolocate = true
    # whether to add ScaleControl
    scale = true
    # whether to add FullscreenControl
    fullscreen = true
  # FixIt 0.2.17 | NEW Donate (Sponsor) settings
  [params.page.reward]
    enable = false
    animation = false
    # position relative to post footer, optional values: ["before", "after"]
    position = "after"
    # comment = "Buy me a coffee"
    # FixIt 0.2.18 | NEW display mode of QR code images, optional values: ["static", "fixed"], default: `static`
    mode = "static"
    [params.page.reward.ways]
      # wechatpay = "/images/wechatpay.png"
      # alipay = "/images/alipay.png"
      # paypal = "/images/paypal.png"
      # bitcoin = "/images/bitcoin.png"

[params.page.share]
  enable = false
# FixIt 0.2.15 | CHANGED Comment config
[params.page.comment]
  enable = true
  [params.page.comment.giscus]
    enable = true
    repo = "weedien/blog"
    repoId = "R_kgDOK2XWaA"
    category = "Announcements"
    categoryId = "DIC_kwDOK2XWaM4Cbia5"
    mapping = "pathname"
    strict = "0"
    term = ""
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "bottom"
    lightTheme = "light"
    darkTheme = "dark"
    lazyLoad = true

[params.page.library]
  [params.page.library.css]
  # someCSS = "some.css"
  # located in "assets/"
  # Or
  # someCSS = "https://cdn.example.com/some.css"
  [params.page.library.js]
# someJavascript = "some.js"
# located in "assets/"
# Or
# someJavascript = "https://cdn.example.com/some.js"
# FixIt 0.2.10 | CHANGED Page SEO config
[params.page.seo]
  # image URL
  images = [  ]
  # Publisher info
  [params.page.seo.publisher]
    name = ""
    logoUrl = ""

[params.typeit]
  speed = 100
  cursorSpeed = 1000
  cursorChar = "|"
  duration = -1
  loop = false

[params.mermaid]
  # For values, see https://mermaid.js.org/config/theming.html#available-themes
  themes = [ "default", "dark" ]

# FixIt 0.2.12 | NEW PanguJS config
[params.pangu]
  # For Chinese writing
  enable = false
  selector = "article" # FixIt 0.2.17 | NEW

# Detail config see https://github.com/Lruihao/watermark#readme
[params.watermark]
  enable = false
  # watermark's text (HTML format is supported)
  content = ""
  # watermark's transparency
  opacity = 0.1
  # parent of watermark's container
  appendTo = ".wrapper>main"
  # watermark's width. unit: px
  width = 150
  # watermark's height. unit: px
  height = 20
  # row spacing of watermarks. unit: px
  rowSpacing = 60
  # col spacing of watermarks. unit: px
  colSpacing = 30
  # watermark's tangent angle. unit: deg
  rotate = 15
  # watermark's fontSize. unit: rem
  fontSize = 0.85
  # FixIt 0.2.13 | NEW watermark's fontFamily
  fontFamily = "inherit"

# FixIt 0.2.12 | NEW Busuanzi count
[params.ibruce]
  enable = false
  # Enable in post meta
  enablePost = false

[params.verification]
  google = ""
  bing = ""
  yandex = ""
  pinterest = ""
  baidu = ""
  so = ""
  sogou = ""

[params.seo]
  # image URL
  image = ""
  # thumbnail URL
  thumbnailUrl = ""

[params.analytics]
  enable = false
  # Google Analytics
  [params.analytics.google]
    id = ""
    # whether to anonymize IP
    anonymizeIP = true
  # Fathom Analytics
  [params.analytics.fathom]
    id = ""
    # server url for your tracker if you're self hosting
    server = ""

[params.cookieconsent]
  enable = false
  # text strings used for Cookie consent banner
  [params.cookieconsent.content]
    message = ""
    dismiss = ""
    link = ""

[params.cdn]
  # CDN data file name, disabled by default ["jsdelivr.yml", "unpkg.yml", ...]
  # located in "themes/FixIt/assets/data/cdn/" directory
  # you can store your own data files in the same path under your project: "assets/data/cdn/"
  data = [ "jsdelivr.yml", "unpkg.yml" ]

[params.compatibility]
  polyfill = false
  objectFit = false

[params.githubCorner]
  enable = false
  permalink = "https://github.com/weedien/blog"
  title = "View source on GitHub"
  position = "right"

# FixIt 0.2.14 | NEW Gravatar config
[params.gravatar]
  # FixIt 0.2.18 | NEW Depends on the author's email, if the author's email is not set, the local avatar will be used
  enable = false
  # Gravatar host, default: "www.gravatar.com"
  host = "www.gravatar.com" # ["cn.gravatar.com", "gravatar.loli.net", ...]
  style = ""                # ["", "mp", "identicon", "monsterid", "wavatar", "retro", "blank", "robohash"]

# FixIt 0.2.16 | NEW Back to top
[params.backToTop]
  enable = true
  # Scroll percent label in b2t button
  scrollpercent = true

[params.readingProgress]
  enable = true
  start = "left"
  position = "top"
  reversed = false
  light = "green"
  dark = "orange"
  height = "3px"

# FixIt 0.2.17 | NEW Progress bar in the top during page loading.
# For more information: https://github.com/CodeByZach/pace
[params.pace]
  enable = true
  # All available colors:
  # ["black", "blue", "green", "orange", "pink", "purple", "red", "silver", "white", "yellow"]
  color = "green"
  # All available themes:
  # ["barber-shop", "big-counter", "bounce", "center-atom", "center-circle", "center-radar", "center-simple",
  # "corner-indicator", "fill-left", "flash", "flat-top", "loading-bar", "mac-osx", "material", "minimal"]
  theme = "bounce"

# FixIt 0.2.18-lts.3 | NEW [Experimental] cache remote images locally, see: https://github.com/hugo-fixit/FixIt/pull/362
[params.cacheRemoteImages]
  enable = false
  # replace remote image url with local image url
  replace = false

# FixIt 0.2.17 | NEW Define custom file paths
# Create your custom files in site directory `layouts/partials/custom` and uncomment needed files below
[params.customFilePath]
  # aside = "custom/aside.html"
  # profile = "custom/profile.html"
  # footer = "custom/footer.html"

# FixIt 0.2.15 | NEW Developer options
[params.dev]
  enable = false
  # Check for updates
  c4u = false
  # Please do not expose to public!
  githubToken = ""
  # Mobile Devtools config
  [params.dev.mDevtools]
    enable = false
    # "vConsole", "eruda" supported
    type = "vConsole"

    # -------------------------------------------------------------------------------------
    # Modules Configuration
    # See: https://gohugo.io/hugo-modules/configuration/#module-config-imports
    # -------------------------------------------------------------------------------------

[module]
  [module.hugoVersion]
    extended = true
    min = "0.110.0"

    # -------------------------------------------------------------------------------------
    # Markup related configuration in Hugo
    # See: https://gohugo.io/getting-started/configuration-markup/
    # -------------------------------------------------------------------------------------

[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    ########## necessary configurations ##########
    # https://github.com/hugo-fixit/FixIt/issues/43
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    ########## necessary configurations ##########
    guessSyntax = true
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      unsafe = true
# Table Of Contents settings
[markup.tableOfContents]
  startLevel = 2
  endLevel = 6

  # -------------------------------------------------------------------------------------
  # Sitemap Configuration
  # See: https://gohugo.io/templates/sitemap-template/#configuration
  # -------------------------------------------------------------------------------------

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

  # -------------------------------------------------------------------------------------
  # Permalinks Configuration
  # See: https://gohugo.io/content-management/urls/#permalinks
  # -------------------------------------------------------------------------------------

[Permalinks]
  # posts = ":year/:month/:filename"
  posts = "posts/:slugorfilename"

  # -------------------------------------------------------------------------------------
  # Privacy Configuration
  # See: https://gohugo.io/about/hugo-and-gdpr/
  # -------------------------------------------------------------------------------------

[privacy]
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

    # -------------------------------------------------------------------------------------
    # Media Types
    # See: https://gohugo.io/templates/output-formats/#media-types
    # -------------------------------------------------------------------------------------

[mediaTypes]
  # Options to make output .md files
  [mediaTypes."text/markdown"]
    suffixes = [ "md" ]
  # Options to make output .txt files
  [mediaTypes."text/plain"]
    suffixes = [ "txt" ]

    # -------------------------------------------------------------------------------------
    # Output Format Definitions
    # See: https://gohugo.io/templates/output-formats/#output-format-definitions
    # -------------------------------------------------------------------------------------

[outputFormats]
  # Options to make output .md files
  [outputFormats.MarkDown]
    mediaType = "text/markdown"
    isPlainText = true
    isHTML = false
  # FixIt 0.2.15 | NEW Options to make output baidu_urls.txt file
  [outputFormats.BaiduUrls]
    baseName = "baidu_urls"
    mediaType = "text/plain"
    isPlainText = true
    isHTML = false
  [outputFormats.Algolia]
    mediaType = "application/json"
    baseName = "algolia"
    isPlainText = true
    notAlternative = true

    # -------------------------------------------------------------------------------------
    # Customizing Output Formats
    # See: https://gohugo.io/templates/output-formats/#customizing-output-formats
    # -------------------------------------------------------------------------------------

[outputs]
  home = [ "HTML", "RSS", "JSON", "BaiduUrls", "Algolia" ]
  page = [ "HTML", "MarkDown" ]
  section = [ "HTML", "RSS" ]
  taxonomy = [ "HTML" ]
  term = [ "HTML", "RSS" ]
